Build started...
Build succeeded.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Contacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Email" text,
    "Phone" text,
    "Username" text,
    "PasswordHash" text,
    "IsAdmin" boolean NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Drivers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "LicenseNumber" text,
    "Phone" text,
    "IsAvailable" boolean NOT NULL,
    CONSTRAINT "PK_Drivers" PRIMARY KEY ("Id")
);

CREATE TABLE "Rooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomNumber" text NOT NULL,
    "RoomType" text NOT NULL,
    "PricePerNight" numeric NOT NULL,
    "Status" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);

CREATE TABLE "Bookings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer,
    "RoomId" integer,
    "DriverId" integer,
    "CheckInDate" timestamp with time zone NOT NULL,
    "CheckOutDate" timestamp with time zone NOT NULL,
    "NumberOfGuests" integer NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Bookings_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
    CONSTRAINT "FK_Bookings_Drivers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Drivers" ("Id"),
    CONSTRAINT "FK_Bookings_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id")
);

CREATE INDEX "IX_Bookings_CustomerId" ON "Bookings" ("CustomerId");

CREATE INDEX "IX_Bookings_DriverId" ON "Bookings" ("DriverId");

CREATE INDEX "IX_Bookings_RoomId" ON "Bookings" ("RoomId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118123141_InitialSchema', '9.0.10');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118123746_AddDescriptionToRooms', '9.0.10');

COMMIT;


